"""
Node 6: Report Generator
- Produces a Markdown report with all findings, charts, and business insights
- Converts to PDF using reportlab
- Exports a Jupyter notebook of all executed code
"""

import os
import json
import nbformat
from datetime import datetime
from agent.state import AgentState, AnalysisStatus
from utils.llm import get_llm
from langchain_core.messages import HumanMessage, SystemMessage


REPORTS_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "reports")
os.makedirs(REPORTS_DIR, exist_ok=True)


def _generate_markdown_report(state: AgentState) -> str:
    """Build the full Markdown report."""

    quality = state.get("data_quality_report", {})
    completed = state.get("completed_tasks", [])
    failed = state.get("failed_tasks", [])
    insights = state.get("business_insights", [])
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    md = f"""# 📊 Autonomous Data Analysis Report
**Dataset:** {state['dataset_name']}
**Generated:** {timestamp}
**Agent:** Autonomous Data Analyst v1.0

---

## 🔍 Data Quality Assessment

| Metric | Value |
|--------|-------|
| Total Rows | {quality.get('total_rows', 'N/A')} |
| Total Columns | {quality.get('total_columns', 'N/A')} |
| Duplicate Rows | {quality.get('duplicate_rows', 0)} |
| Quality Score | **{quality.get('quality_score', 0)}/100** |

"""

    if quality.get("missing_values"):
        md += "**Missing Values:**\n"
        for col, count in quality["missing_values"].items():
            md += f"- `{col}`: {count} missing\n"
        md += "\n"

    if quality.get("outlier_columns"):
        md += f"**Outliers Detected In:** {', '.join(quality['outlier_columns'][:5])}\n\n"

    if quality.get("recommendations"):
        md += "**Recommendations:**\n"
        for rec in quality["recommendations"]:
            md += f"- {rec}\n"
        md += "\n"

    md += "---\n\n## 📈 Analysis Results\n\n"

    for i, task in enumerate(completed, 1):
        if task["status"] != AnalysisStatus.COMPLETED:
            continue

        confidence = task.get("confidence_score", 0)
        conf_emoji = "🟢" if confidence >= 0.8 else "🟡" if confidence >= 0.5 else "🔴"

        md += f"### {i}. {task['title']}\n"
        md += f"*Type: {task['analysis_type']} | Confidence: {conf_emoji} {confidence:.0%}*\n\n"

        if task.get("interpretation"):
            md += f"{task['interpretation']}\n\n"

        if task.get("chart_path") and os.path.exists(task["chart_path"]):
            chart_name = os.path.basename(task["chart_path"])
            md += f"![{task['title']}](charts/{chart_name})\n\n"

        if task.get("assumptions"):
            md += f"*Assumptions: {'; '.join(task['assumptions'])}*\n\n"

        md += "---\n\n"

    if failed:
        md += "## ⚠️ Failed Analyses\n\n"
        for task in failed:
            md += f"- **{task['title']}**: {task.get('error_message', 'Unknown error')[:150]}\n"
        md += "\n---\n\n"

    if insights:
        md += "## 💡 Key Business Insights\n\n"
        for insight in insights:
            md += f"- {insight}\n"
        md += "\n---\n\n"

    # Execution timeline
    md += "## ⏱️ Execution Timeline\n\n"
    md += "| Time | Node | Action | Status |\n"
    md += "|------|------|--------|--------|\n"
    for entry in state.get("execution_log", []):
        ts = entry.get("timestamp", "")[:19].replace("T", " ")
        node = entry.get("node", "")
        action = entry.get("action", "")[:50]
        status = entry.get("status", "")
        md += f"| {ts} | {node} | {action} | {status} |\n"

    md += "\n---\n*Generated by Autonomous Data Analyst Agent*\n"
    return md


def _export_notebook(state: AgentState, report_path: str) -> str:
    """Create a Jupyter notebook of all executed code."""
    nb = nbformat.v4.new_notebook()
    cells = []

    # Title cell
    cells.append(nbformat.v4.new_markdown_cell(
        f"# Data Analysis: {state['dataset_name']}\n"
        f"*Generated by Autonomous Data Analyst Agent*\n\n"
        f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M')}"
    ))

    # Setup cell
    cells.append(nbformat.v4.new_code_cell(
        "import pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt\n"
        "import seaborn as sns\nimport warnings\nwarnings.filterwarnings('ignore')\n"
        f"df = pd.read_csv('{state['csv_path']}')\nprint(df.shape)"
    ))

    # One cell per completed task
    for task in state.get("completed_tasks", []):
        if task.get("generated_code"):
            cells.append(nbformat.v4.new_markdown_cell(
                f"## {task['title']}\n*{task['description']}*"
            ))
            # Replace CHART_PATH with a display-friendly version
            code = task["generated_code"].replace(
                "plt.savefig(CHART_PATH, bbox_inches='tight')\nplt.close('all')",
                "plt.tight_layout()\nplt.show()"
            )
            code = f"CHART_PATH = 'chart_{task['id']}.png'\n\n" + code
            cells.append(nbformat.v4.new_code_cell(code))

            if task.get("interpretation"):
                cells.append(nbformat.v4.new_markdown_cell(
                    f"**Insight:** {task['interpretation']}\n\n"
                    f"*Confidence: {task.get('confidence_score', 0):.0%}*"
                ))

    nb.cells = cells
    notebook_path = os.path.join(REPORTS_DIR, f"{state['dataset_name'].replace(' ', '_')}_analysis.ipynb")
    with open(notebook_path, "w") as f:
        nbformat.write(nb, f)

    return notebook_path


def _generate_pdf(markdown_content: str, output_path: str) -> str:
    """Convert markdown to PDF using reportlab."""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage
        from reportlab.lib import colors
        import re

        pdf_path = output_path.replace(".md", ".pdf")
        doc = SimpleDocTemplate(pdf_path, pagesize=A4,
                                rightMargin=inch * 0.75, leftMargin=inch * 0.75,
                                topMargin=inch, bottomMargin=inch)

        styles = getSampleStyleSheet()
        story = []

        for line in markdown_content.split("\n"):
            line = line.strip()
            if not line:
                story.append(Spacer(1, 6))
            elif line.startswith("# "):
                story.append(Paragraph(line[2:], styles["Title"]))
                story.append(Spacer(1, 12))
            elif line.startswith("## "):
                story.append(Paragraph(line[3:], styles["Heading1"]))
                story.append(Spacer(1, 8))
            elif line.startswith("### "):
                story.append(Paragraph(line[4:], styles["Heading2"]))
                story.append(Spacer(1, 6))
            elif line.startswith("- ") or line.startswith("* "):
                story.append(Paragraph(f"• {line[2:]}", styles["Normal"]))
            elif line.startswith("---"):
                story.append(Spacer(1, 12))
            elif line.startswith("!["):
                # Try to embed chart image
                img_match = re.search(r'\(charts/(.+?)\)', line)
                if img_match:
                    chart_path = os.path.join(REPORTS_DIR, "charts", img_match.group(1))
                    if os.path.exists(chart_path):
                        try:
                            img = RLImage(chart_path, width=5*inch, height=3*inch)
                            story.append(img)
                            story.append(Spacer(1, 8))
                        except Exception:
                            pass
            elif line and not line.startswith("|"):
                # Clean markdown formatting for PDF
                clean = re.sub(r'\*\*(.+?)\*\*', r'\1', line)
                clean = re.sub(r'\*(.+?)\*', r'\1', clean)
                clean = re.sub(r'`(.+?)`', r'\1', clean)
                story.append(Paragraph(clean, styles["Normal"]))

        doc.build(story)
        return pdf_path

    except Exception as e:
        return f"PDF generation failed: {str(e)}"


def report_generator_node(state: AgentState) -> AgentState:
    """Generate Markdown report, PDF, and Jupyter notebook."""

    log_entry = {
        "timestamp": datetime.now().isoformat(),
        "node": "report_generator",
        "action": "Generating final report"
    }

    try:
        # Markdown
        md_content = _generate_markdown_report(state)
        md_path = os.path.join(REPORTS_DIR, f"{state['dataset_name'].replace(' ', '_')}_report.md")
        with open(md_path, "w", encoding="utf-8") as f:
            f.write(md_content)

        # PDF
        pdf_path = _generate_pdf(md_content, md_path)

        # Jupyter notebook
        notebook_path = _export_notebook(state, md_path)

        log_entry["status"] = "success"
        log_entry["detail"] = f"Report: {md_path} | PDF: {pdf_path} | Notebook: {notebook_path}"

        return {
            **state,
            "final_report_md": md_path,
            "final_report_pdf": pdf_path if "failed" not in str(pdf_path) else None,
            "notebook_path": notebook_path,
            "execution_log": state.get("execution_log", []) + [log_entry],
            "next_action": "done"
        }

    except Exception as e:
        log_entry["status"] = "error"
        log_entry["detail"] = str(e)
        return {
            **state,
            "error_message": f"Report generation failed: {str(e)}",
            "execution_log": state.get("execution_log", []) + [log_entry],
            "next_action": "done"
        }
